services:
  app:
    build: .
    container_name: ecommerce-api-app
    environment:
      TZ: Europe/Istanbul
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - mailhog

  web:
    image: nginx:latest
    container_name: ecommerce-api-web
    environment:
      TZ: Europe/Istanbul
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: postgres:13
    container_name: ecommerce-api-db
    environment:
      TZ: Europe/Istanbul
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecommerce_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ecommerce-api-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"    # SMTP portu
      - "8025:8025"    # Web UI (http://localhost:8025)    

volumes:
  pgdata:
