services:
  app:
    build: .
    container_name: ecommerce-api-app
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: ecommerce-api-web
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: postgres:13
    container_name: ecommerce-api-db
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecommerce_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
